
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace r3mus.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Announcement
{

    public Nullable<long> Id { get; set; }

    public string Category { get; set; }

    public string Topic { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public string Post { get; set; }

    public string UserName { get; set; }

    public string Avatar { get; set; }

}

}
