

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace r3mus.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class ApplicantEntities : DbContext
{
    public ApplicantEntities()
        : base("name=ApplicantEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<ApplicantList> ApplicantLists { get; set; }


    public virtual ObjectResult<MarkRecruitmentMailees_Result> MarkRecruitmentMailees(string userID)
    {

        var userIDParameter = userID != null ?
            new ObjectParameter("UserID", userID) :
            new ObjectParameter("UserID", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MarkRecruitmentMailees_Result>("MarkRecruitmentMailees", userIDParameter);
    }


    public virtual int CloseRecruitmentMailees(string names)
    {

        var namesParameter = names != null ?
            new ObjectParameter("Names", names) :
            new ObjectParameter("Names", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CloseRecruitmentMailees", namesParameter);
    }


    public virtual int UnlockRecruitmentMailees(string names)
    {

        var namesParameter = names != null ?
            new ObjectParameter("Names", names) :
            new ObjectParameter("Names", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UnlockRecruitmentMailees", namesParameter);
    }

}

}

