//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace r3mus.Models
{
    using Microsoft.AspNet.Identity;
    using Microsoft.AspNet.Identity.EntityFramework;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity;
    using System.Linq;
    using System.Web;
    public partial class RecruitmentMailee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime Submitted { get; set; }
        public DateTime? Mailed { get; set; }
        public string SubmitterId { get; set; }
        public string MailerId { get; set; }
        public DateTime? DateOfBirth { get; set; }

        public long CorpId_AtLastCheck { get; set; }

        public DateTime LastUpdated { get; set; }
    }
}
